spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/student_crud_api
    username: postgres
    password: "abc@123"
  output:
    ansi:
      enabled: always
  devtools:
    add-properties: false
